<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7zZ0To\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7zZ0To/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY7zZ0To.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY7zZ0To\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY7zZ0To\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y7zZ0To',
    'container.build_id' => '3b124528',
    'container.build_time' => 1730602104,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7zZ0To');
