<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBRtJUZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBRtJUZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBRtJUZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBRtJUZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBRtJUZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBRtJUZ',
    'container.build_id' => 'daa9c6de',
    'container.build_time' => 1730634651,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBRtJUZ');
