<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGgMN1hR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGgMN1hR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGgMN1hR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGgMN1hR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGgMN1hR\App_KernelDevDebugContainer([
    'container.build_hash' => 'GgMN1hR',
    'container.build_id' => 'b27bbdd6',
    'container.build_time' => 1730745136,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGgMN1hR');
